In [1]:
import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from allensdk.brain_observatory.ecephys.ecephys_project_cache import EcephysProjectCache

In [2]:
from tempfile import TemporaryFile

In [3]:
manifest_path = os.path.join('ecephys_cache_dir/', "manifest.json")

cache = EcephysProjectCache.from_warehouse(manifest=manifest_path)

print(cache.get_all_session_types())

['brain_observatory_1.1', 'functional_connectivity']


In [4]:
sessions = cache.get_session_table()
brain_observatory_type_sessions = sessions[sessions["session_type"] == "brain_observatory_1.1"]
brain_observatory_type_sessions.tail()

published_at  specimen_id           session_type  \
id                                                                    
773418906  2019-10-03T00:00:00Z    757329624  brain_observatory_1.1   
791319847  2019-10-03T00:00:00Z    769360779  brain_observatory_1.1   
797828357  2019-10-03T00:00:00Z    776061251  brain_observatory_1.1   
798911424  2019-10-03T00:00:00Z    775876828  brain_observatory_1.1   
799864342  2019-10-03T00:00:00Z    772616823  brain_observatory_1.1   

           age_in_days sex                                    full_genotype  \
id                                                                            
773418906        124.0   F  Pvalb-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt   
791319847        116.0   M    Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt   
797828357        107.0   M  Pvalb-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt   
798911424        110.0   F    Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt   
799864342        129.0   M                                            wt/wt   

           unit_count  channel_count  probe_count  \
id                                                  
773418906         546           2232            6   
791319847         555           2229            6   
797828357         611           2232            6   
798911424         825           2233            6   
799864342         604           2233            6   

                                  ecephys_structure_acronyms  
id                                                            
773418906  [PPT, NOT, SUB, ProS, CA1, VISam, nan, APN, DG...  
791319847  [APN, DG, CA1, VISam, nan, LP, TH, VISpm, POL,...  
797828357  [PPT, MB, APN, NOT, HPF, ProS, CA1, VISam, nan...  
798911424  [APN, TH, Eth, LP, DG, HPF, CA3, CA1, VISrl, n...  
799864342  [APN, POL, LP, DG, CA1, VISrl, nan, LGd, CA3, ...

In [5]:
brain_observatory_type_sessions.head()

published_at  specimen_id           session_type  \
id                                                                    
715093703  2019-10-03T00:00:00Z    699733581  brain_observatory_1.1   
719161530  2019-10-03T00:00:00Z    703279284  brain_observatory_1.1   
721123822  2019-10-03T00:00:00Z    707296982  brain_observatory_1.1   
732592105  2019-10-03T00:00:00Z    717038288  brain_observatory_1.1   
737581020  2019-10-03T00:00:00Z    718643567  brain_observatory_1.1   

           age_in_days sex                                    full_genotype  \
id                                                                            
715093703        118.0   M    Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt   
719161530        122.0   M    Sst-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt   
721123822        125.0   M  Pvalb-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt   
732592105        100.0   M                                            wt/wt   
737581020        108.0   M                                            wt/wt   

           unit_count  channel_count  probe_count  \
id                                                  
715093703         884           2219            6   
719161530         755           2214            6   
721123822         444           2229            6   
732592105         824           1847            5   
737581020         568           2218            6   

                                  ecephys_structure_acronyms  
id                                                            
715093703  [CA1, VISrl, nan, PO, LP, LGd, CA3, DG, VISl, ...  
719161530  [TH, Eth, APN, POL, LP, DG, CA1, VISpm, nan, N...  
721123822  [MB, SCig, PPT, NOT, DG, CA1, VISam, nan, LP, ...  
732592105       [grey, VISpm, nan, VISp, VISl, VISal, VISrl]  
737581020      [grey, VISmma, nan, VISpm, VISp, VISl, VISrl]

In [6]:
sesh_id = 798911424
session = cache.get_session_data(sesh_id)

In [7]:
session.metadata

{'specimen_name': 'Vip-IRES-Cre;Ai32-421338',
 'session_type': 'brain_observatory_1.1',
 'full_genotype': 'Vip-IRES-Cre/wt;Ai32(RCL-ChR2(H134R)_EYFP)/wt',
 'sex': 'F',
 'age_in_days': 110.0,
 'rig_equipment_name': 'NP.1',
 'num_units': 825,
 'num_channels': 2233,
 'num_probes': 6,
 'num_stimulus_presentations': 70931,
 'session_start_time': datetime.datetime(2018, 12, 21, 0, 2, 57, tzinfo=tzoffset(None, -28800)),
 'ecephys_session_id': 798911424,
 'structure_acronyms': ['LP',
  'DG',
  'CA1',
  'VISam',
  nan,
  'APN',
  'TH',
  'Eth',
  'CA3',
  'VISrl',
  'HPF',
  'ProS',
  'SUB',
  'VISp',
  'CA2',
  'VISl',
  'MB',
  'NOT',
  'LGv',
  'VISal'],
 'stimulus_names': ['spontaneous',
  'gabors',
  'flashes',
  'drifting_gratings',
  'natural_movie_three',
  'natural_movie_one',
  'static_gratings',
  'natural_scenes',
  'drifting_gratings_contrast']}

In [14]:
session.stimulus_presentations["stimulus_block"]

stimulus_presentation_id
0        null
1           0
2           0
3           0
4           0
         ... 
70926      15
70927      15
70928      15
70929      15
70930      15
Name: stimulus_block, Length: 70931, dtype: object

In [8]:
session.structurewise_unit_counts

VISam    135
CA1      134
VISp      94
VISal     89
VISl      78
LP        65
SUB       59
VISrl     47
DG        31
APN       25
CA3       21
NOT       16
LGv       16
ProS       9
CA2        2
TH         2
Eth        1
MB         1
Name: ecephys_structure_acronym, dtype: int64

In [51]:
# presentations = session.get_stimulus_table("natural_scenes")
presentations = session.stimulus_presentations.loc[
    session.stimulus_presentations["stimulus_block"] == 1]
units = session.units[session.units["ecephys_structure_acronym"] == 'CA1']
print(len(units))

spikes = session.presentationwise_spike_times(
    stimulus_presentation_ids=presentations.index.values,
    unit_ids=units.index.values[:]
)

spikes

134


stimulus_presentation_id    unit_id  \
spike_time                                         
1285.930825                      3647  951106592   
1285.932243                      3647  951091444   
1285.932992                      3647  951106229   
1285.933082                      3647  951116003   
1285.934892                      3647  951106493   
...                               ...        ...   
1584.399289                      3796  951106592   
1584.405789                      3796  951108131   
1584.413116                      3796  951112147   
1584.414548                      3796  951091412   
1584.415949                      3796  951112067   

             time_since_stimulus_presentation_onset  
spike_time                                           
1285.930825                                0.001039  
1285.932243                                0.002457  
1285.932992                                0.003206  
1285.933082                                0.003296  
1285.934892                                0.005106  
...                                             ...  
1584.399289                                0.220212  
1584.405789                                0.226712  
1584.413116                                0.234039  
1584.414548                                0.235472  
1584.415949                                0.236873  

[43330 rows x 3 columns]

In [52]:
def get_num(column):
    ids = spikes.loc[:, column].to_numpy()
    sets = set(ids)

    map_ = {}
    num = 1
    for id_ in ids:
        if id_ not in map_: 
            map_[id_] = num
            num += 1
        if len(map_.keys()) == len(sets):
            break
    return len(sets), map_, ids

In [53]:
num_stim, stim_map, stim_ids = get_num("stimulus_presentation_id")
print(num_stim)
print(stim_map)

150
{3647: 1, 3648: 2, 3649: 3, 3650: 4, 3651: 5, 3652: 6, 3653: 7, 3654: 8, 3655: 9, 3656: 10, 3657: 11, 3658: 12, 3659: 13, 3660: 14, 3661: 15, 3662: 16, 3663: 17, 3664: 18, 3665: 19, 3666: 20, 3667: 21, 3668: 22, 3669: 23, 3670: 24, 3671: 25, 3672: 26, 3673: 27, 3674: 28, 3675: 29, 3676: 30, 3677: 31, 3678: 32, 3679: 33, 3680: 34, 3681: 35, 3682: 36, 3683: 37, 3684: 38, 3685: 39, 3686: 40, 3687: 41, 3688: 42, 3689: 43, 3690: 44, 3691: 45, 3692: 46, 3693: 47, 3694: 48, 3695: 49, 3696: 50, 3697: 51, 3698: 52, 3699: 53, 3700: 54, 3701: 55, 3702: 56, 3703: 57, 3704: 58, 3705: 59, 3706: 60, 3707: 61, 3708: 62, 3709: 63, 3710: 64, 3711: 65, 3712: 66, 3713: 67, 3714: 68, 3715: 69, 3716: 70, 3717: 71, 3718: 72, 3719: 73, 3720: 74, 3721: 75, 3722: 76, 3723: 77, 3724: 78, 3725: 79, 3726: 80, 3727: 81, 3728: 82, 3729: 83, 3730: 84, 3731: 85, 3732: 86, 3733: 87, 3734: 88, 3735: 89, 3736: 90, 3737: 91, 3738: 92, 3739: 93, 3740: 94, 3741: 95, 3742: 96, 3743: 97, 3744: 98, 3745: 99, 3746: 100, 374

In [19]:
stims = np.array([stim_map[i] for i in stim_ids])
print(stims.shape)
print(stims)

np.save('ad_gabors_stim_ids.npy', stims)

(223684,)
[   1    1    1 ... 3644 3644 3644]


In [54]:
np.save('adf_spike_times_ca1.npy', spikes.index.to_numpy())

In [55]:
num_neur, neur_map, neur_ids = get_num("unit_id")
print(neur_map)
print(len(neur_map))

{951106592: 1, 951091444: 2, 951106229: 3, 951116003: 4, 951106493: 5, 951091188: 6, 951106105: 7, 951106126: 8, 951106725: 9, 951090551: 10, 951107278: 11, 951106278: 12, 951107266: 13, 951111734: 14, 951108120: 15, 951112225: 16, 951107474: 17, 951096918: 18, 951097339: 19, 951107200: 20, 951110228: 21, 951091412: 22, 951091785: 23, 951106047: 24, 951116332: 25, 951094300: 26, 951091492: 27, 951111470: 28, 951106581: 29, 951106527: 30, 951106891: 31, 951106759: 32, 951116313: 33, 951096869: 34, 951111836: 35, 951116395: 36, 951090804: 37, 951111827: 38, 951116440: 39, 951116459: 40, 951111680: 41, 951106458: 42, 951112067: 43, 951106677: 44, 951097368: 45, 951116248: 46, 951096645: 47, 951106851: 48, 951112147: 49, 951094268: 50, 951107814: 51, 951112080: 52, 951111383: 53, 951090729: 54, 951107801: 55, 951116030: 56, 951096947: 57, 951106376: 58, 951107585: 59, 951106922: 60, 951090343: 61, 951090679: 62, 951111478: 63, 951091287: 64, 951108131: 65, 951106071: 66, 951112116: 67, 951

In [56]:
neurons = np.array([neur_map[i] for i in neur_ids])
print(neurons.shape)
print(neurons)

(43330,)
[ 1  2  3 ... 49 22 43]


In [57]:
np.save('adf_spike_ids_ca1.npy', neurons)

In [45]:
df_probes = cache.get_probes()

df_probes.loc[df_probes['ecephys_session_id'] == sesh_id]

ecephys_session_id  lfp_sampling_rate    name phase  sampling_rate  \
id                                                                              
800036196           798911424        1249.998582  probeA    3a   29999.965974   
800036198           798911424        1249.996550  probeB    3a   29999.917201   
800036200           798911424        1249.999835  probeC    3a   29999.996048   
800036202           798911424        1249.996662  probeD    3a   29999.919900   
800036204           798911424        1249.999976  probeE    3a   29999.999422   
800036206           798911424        1250.001602  probeF    3a   30000.038460   

           has_lfp_data  unit_count  channel_count  \
id                                                   
800036196          True         143            374   
800036198          True         118            368   
800036200          True         167            374   
800036202          True         129            372   
800036204          True         152            374   
800036206          True         116            371   

                                  ecephys_structure_acronyms  
id                                                            
800036196                [APN, MB, NOT, DG, CA1, VISam, nan]  
800036198                          [LP, DG, CA1, VISam, nan]  
800036200                         [DG, ProS, SUB, VISp, nan]  
800036202                         [CA3, CA2, CA1, VISl, nan]  
800036204                   [LGv, CA3, CA2, CA1, VISal, nan]  
800036206  [APN, TH, Eth, LP, DG, HPF, CA3, CA1, VISrl, nan]

In [49]:
stim_df = session.stimulus_presentations
# flashes = 'flashes'
scenes_df = stim_df.loc[stim_df["stimulus_block"] == 9]

scenes_df

color contrast frame orientation phase  size  \
stimulus_presentation_id                                                
51355                     null     null    13        null  null  null   
51356                     null     null    38        null  null  null   
51357                     null     null    30        null  null  null   
51358                     null     null    35        null  null  null   
51359                     null     null   112        null  null  null   
...                        ...      ...   ...         ...   ...   ...   
53270                     null     null    91        null  null  null   
53271                     null     null   106        null  null  null   
53272                     null     null    62        null  null  null   
53273                     null     null    54        null  null  null   
53274                     null     null    52        null  null  null   

                         spatial_frequency   start_time stimulus_block  \
stimulus_presentation_id                                                 
51355                                 null  5909.794447              9   
51356                                 null  5910.044666              9   
51357                                 null  5910.294885              9   
51358                                 null  5910.545104              9   
51359                                 null  5910.795324              9   
...                                    ...          ...            ...   
53270                                 null  6388.944962              9   
53271                                 null  6389.195174              9   
53272                                 null  6389.445392              9   
53273                                 null  6389.695610              9   
53274                                 null  6389.945828              9   

                           stimulus_name    stop_time temporal_frequency  \
stimulus_presentation_id                                                   
51355                     natural_scenes  5910.044666               null   
51356                     natural_scenes  5910.294885               null   
51357                     natural_scenes  5910.545104               null   
51358                     natural_scenes  5910.795324               null   
51359                     natural_scenes  5911.045522               null   
...                                  ...          ...                ...   
53270                     natural_scenes  6389.195174               null   
53271                     natural_scenes  6389.445392               null   
53272                     natural_scenes  6389.695610               null   
53273                     natural_scenes  6389.945828               null   
53274                     natural_scenes  6390.196047               null   

                         x_position y_position  duration  \
stimulus_presentation_id                                   
51355                          null       null  0.250219   
51356                          null       null  0.250219   
51357                          null       null  0.250219   
51358                          null       null  0.250219   
51359                          null       null  0.250198   
...                             ...        ...       ...   
53270                          null       null  0.250212   
53271                          null       null  0.250218   
53272                          null       null  0.250218   
53273                          null       null  0.250218   
53274                          null       null  0.250218   

                          stimulus_condition_id  
stimulus_presentation_id                         
51355                                      4908  
51356                                      4909  
51357                                      4910  
51358                                      4911  
51359                                     

In [50]:
gabors_df_frame = scenes_df[["frame", "start_time", "stop_time"]]
np_scenes = gabors_df_frame.to_numpy()
print(np_scenes)

[[13.0 5909.79444656101 5910.04466580433]
 [38.0 5910.04466580433 5910.294885047651]
 [30.0 5910.294885047651 5910.545104290973]
 ...
 [62.0 6389.445391790971 6389.695610047653]
 [54.0 6389.695610047653 6389.94582830433]
 [52.0 6389.94582830433 6390.196046561009]]


In [106]:
np.save('ad_scenes_frame_times.npy', np_scenes)

In [72]:
session.stimulus_names

['spontaneous',
 'gabors',
 'flashes',
 'drifting_gratings',
 'natural_movie_three',
 'natural_movie_one',
 'static_gratings',
 'natural_scenes',
 'drifting_gratings_contrast']

In [73]:
session.get_stimulus_epochs()

start_time    stop_time    duration               stimulus_name  \
0     24.875987    84.942787   60.066800                 spontaneous   
1     84.942787   996.938254  911.995468                      gabors   
2    996.938254  1285.929787  288.991532                 spontaneous   
3   1285.929787  1584.429283  298.499497                     flashes   
4   1584.429283  1586.180717    1.751433                 spontaneous   
5   1586.180717  2185.681814  599.501097           drifting_gratings   
6   2185.681814  2216.707717   31.025903                 spontaneous   
7   2216.707717  2817.209647  600.501930         natural_movie_three   
8   2817.209647  2847.234747   30.025100                 spontaneous   
9   2847.234747  3147.485707  300.250960           natural_movie_one   
10  3147.485707  3177.510797   30.025090                 spontaneous   
11  3177.510797  3777.011874  599.501077           drifting_gratings   
12  3777.011874  4078.263667  301.251793                 spontaneous   
13  4078.263667  4678.765587  600.501920         natural_movie_three   
14  4678.765587  4708.790697   30.025110                 spontaneous   
15  4708.790697  5398.367024  689.576327           drifting_gratings   
16  5398.367024  5399.367847    1.000823                 spontaneous   
17  5399.367847  5879.769367  480.401520             static_gratings   
18  5879.769367  5909.794447   30.025080                 spontaneous   
19  5909.794447  6390.196047  480.401600              natural_scenes   
20  6390.196047  6690.446947  300.250900                 spontaneous   
21  6690.446947  7170.848457  480.401510              natural_scenes   
22  7170.848457  7200.873547   30.025090                 spontaneous   
23  7200.873547  7681.275097  480.401550             static_gratings   
24  7681.275097  7711.300177   30.025080                 spontaneous   
25  7711.300177  8011.551127  300.250950           natural_movie_one   
26  8011.551127  8041.576237   30.025110                 spontaneous   
27  8041.576237  8569.517485  527.941248              natural_scenes   
28  8569.517485  8612.053037   42.535552                 spontaneous   
29  8612.053037  9152.504767  540.451730             static_gratings   
30  9152.504767  9182.529857   30.025090                 spontaneous   
31  9182.529857  9722.497795  539.967938  drifting_gratings_contrast   

   stimulus_block  
0            null  
1               0  
2            null  
3               1  
4            null  
5               2  
6            null  
7               3  
8            null  
9               4  
10           null  
11              5  
12           null  
13              6  
14           null  
15              7  
16           null  
17              8  
18           null  
19              9  
20           null  
21             10  
22           null  
23             11  
24           null  
25             12  
26           null  
27             13  
28           null  
29             14  
30           null  
31             15